---
- hosts: web

  tasks:
    - name: Install Prerequisites
      apt:
        name:
          - gcc
          - build-essential
          - g++
          - perl
          - dkms
        state: present

    - name: Download and install the node feed
      shell:
        cmd: curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash

    - name: Install NodeJS
      apt:
        name: nodejs
        state: present

    - name: Install Python3
      apt:
        name: python3
        state: present

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Install Gunicorns
      apt:
        name: gunicorn
        state: present

    - name: Ensure NGINX servirce is running
      service:
        name: nginx
        state: started

    # - name: Creates directory
    #   file:
    #     path: "/var/www/online"
    #     state: directory

    - name: Create test file
      copy:
        dest: "/var/www/html/index.html"
        content: "<!DOCTYPE html><html><body>online</body></html>"

    # - name: Configure Gunicorn App
    #   gunicorn:
    #     app: todo
    #     chdir: "/var/www/todo"
