---
- hosts: web
  become: yes

  tasks:
    - name: Add the jenkins user
      user:
        name: jenkins
        shell: /bin/bash
        # update_password: always
        # password: OZJiasFFl9ev6
        # password: "{{ newpassword|password_hash('sha512') }}"
        password: $2y$10$4DdqQTudi9kvY.NRVKVIP.XDwpwcp7njISHYQAcBH9ERcI2vYGaiC
        groups: adm,sudo,dip,plugdev,lxd
        append: yes
        state: present

    - name: Make jenkins part of sudoers.d
      copy:
        dest: "/etc/sudoers.d/jenkins"
        content: "jenkins ALL=(ALL) NOPASSWD:ALL"

    # - name: Set jenkins user password to blank
    #   command: sudo passwd -d jenkins

    # - name: Expire jenkins user password
    #   command: sudo chage -d 0 jenkins

    # - name: Set authorized key taken for ansible user
    #   authorized_key:
    #     user: ansible
    #     state: present
    #     key: "{{ lookup('file', '/home/alexandr/devops/ansible/ansible_key.pub') }}"
